version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-mariadb
    ports:
      - '${PORT}:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
